animations {
    enabled = yes

    bezier = easeOutQuint,   0.23, 1,    0.32, 1
    bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
    bezier = linear,         0,    0,    1,    1
    bezier = almostLinear,   0.5,  0.5,  0.75, 1
    bezier = quick,          0.15, 0,    0.1,  1

    animation = global,        1, 10, default

    animation = border,        1, 8, easeOutQuint
    animation = windows,       1, 5, easeOutQuint
    animation = windowsIn,     1, 5, easeOutQuint, popin 90%
    animation = windowsOut,    1, 3, easeOutQuint, popin 90%

    animation = fade,          1, 5, quick
    animation = fadeIn,        1, 4, easeOutQuint
    animation = fadeOut,       1, 4, easeOutQuint

    animation = layers,        1, 5, easeOutQuint
    animation = layersIn,      1, 5, easeOutQuint
    animation = layersOut,     1, 4, easeOutQuint

    animation = fadeLayersIn,  1, 4, easeOutQuint
    animation = fadeLayersOut, 1, 4, easeOutQuint

    animation = workspaces,    1, 7, easeOutQuint

    animation = zoomFactor,    1, 7, quick
}
