#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox

exec-once = ~/.config/waybar/scripts/launch.sh
exec-once = swww-daemon


exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data

exec-once = wl-clip-persist --clipboard regular

exec-once = gsettings set org.gnome.desktop.interface icon-theme "GreyStone"
exec-once = nm-applet --indicator
exec-once = hypridle
# exec-once = rm -f /tmp/hypr-smart-fullscreen.lock && bash /usr/local/bin/hypr-smart-fullscreen.sh
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
